services:
  - type: web
    name: big-dad
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: database
    buildCommand: composer install --optimize-autoloader --no-dev && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT

databases:
  - name: big-dad-db
    databaseName: big_dad
    user: big_dad_user
